spring:
  application:
    name: catalog-service
  config:
    import: "optional:configserver:" # remove optional in production
  cloud:
    config:
      uri: http://localhost:8888
      request-connect-timeout: 5000
      request-read-timeout: 5000
      fail-fast: false # set true in production
      retry:
        max-attempts: 6
        initial-interval: 1000
        max-interval: 2000
        multiplier: 1.1
  datasource:
    url: jdbc:postgresql://localhost:5432/book_catalog
    username: user
    password: password
    hikari:
      connection-timeout: 2000
      maximum-pool-size: 5

management:
  endpoints:
    web:
      exposure:
        include: refresh # Exposes the POST /actuator/refresh endpoint through HTTP

server:
  port: 9001
  tomcat:
    connection-timeout: 2s
    keep-alive-timeout: 15s
    threads:
      max: 50
      min-spare: 5

oddbooks:
  greeting: "[default profile] Hello World!"